# Generated by Django 4.1 on 2023-01-20 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('date_purchase', models.DateField(blank=True, null=True, verbose_name='Fecha de compra')),
                ('product_number', models.CharField(max_length=150, verbose_name='Número de producto')),
                ('inventory_number', models.IntegerField(unique=True, verbose_name='Número de inventario')),
                ('serial_number', models.CharField(max_length=150, unique=True, verbose_name='Número de serie')),
                ('state', models.CharField(choices=[('Activo asignado', 'Activo asignado'), ('Activo disponible', 'Activo disponible'), ('Mantenimiento', 'Mantenimiento'), ('Dado de baja', 'Dado de baja'), ('Por definir', 'Por definir')], default='Por definir', max_length=20, verbose_name='Estado')),
                ('processor', models.CharField(blank=True, max_length=500, null=True, verbose_name='Procesador')),
                ('ram_memory', models.CharField(blank=True, max_length=500, null=True, verbose_name='Memoria RAM')),
                ('disk_memory', models.CharField(blank=True, max_length=500, null=True, verbose_name='Disco Duro')),
                ('graphics', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tarjeta gráfica')),
                ('monitor_screen', models.CharField(blank=True, max_length=500, null=True, verbose_name='Pantalla')),
                ('operative_system', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sistema Operativo')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Computador',
                'verbose_name_plural': 'Computadores',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('type_manufacturer', models.CharField(choices=[('Para equipos', 'Para equipos'), ('Para monitor', 'Para monitor'), ('Para dispositivos', 'Para dispositivos'), ('Todos', 'Todos')], max_length=20, verbose_name='Tipo de fabricante')),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
            },
        ),
        migrations.CreateModel(
            name='ModelManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_image', verbose_name='Imagen producto')),
                ('type_model', models.CharField(choices=[('Para equipos', 'Para equipos'), ('Para monitor', 'Para monitor'), ('Para dispositivos', 'Para dispositivos'), ('Todos', 'Todos')], max_length=20, verbose_name='Tipo de modelo')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actives.manufacturer', verbose_name='Fabricante')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
            },
        ),
        migrations.CreateModel(
            name='TypeDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Dispositivos',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='PassiveDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre activo')),
                ('date_purchase', models.DateField(blank=True, null=True, verbose_name='Fecha de compra')),
                ('state', models.CharField(choices=[('Activo asignado', 'Activo asignado'), ('Activo disponible', 'Activo disponible'), ('Mantenimiento', 'Mantenimiento'), ('Dado de baja', 'Dado de baja'), ('Por definir', 'Por definir')], default='Por definir', max_length=20, verbose_name='Estado')),
                ('inventory_number', models.IntegerField(unique=True, verbose_name='Número de inventario')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Observaciones')),
                ('location', models.CharField(max_length=150, verbose_name='Ubicación')),
                ('serial_number', models.CharField(max_length=150, unique=True, verbose_name='Número de serie')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actives.modelmanufacturer', verbose_name='Fabricante - Modelo')),
                ('type_devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actives.typedevices', verbose_name='Tipo dispositivo')),
            ],
            options={
                'verbose_name': 'Dispositivo Pasivo',
                'verbose_name_plural': 'Dispositivos Pasivos',
            },
        ),
        migrations.CreateModel(
            name='Monitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('date_purchase', models.DateField(blank=True, null=True, verbose_name='Fecha de compra')),
                ('product_number', models.CharField(max_length=150, verbose_name='Número de producto')),
                ('inventory_number', models.IntegerField(unique=True, verbose_name='Número de inventario')),
                ('serial_number', models.CharField(max_length=150, unique=True, verbose_name='Número de serie')),
                ('state', models.CharField(choices=[('Activo asignado', 'Activo asignado'), ('Activo disponible', 'Activo disponible'), ('Mantenimiento', 'Mantenimiento'), ('Dado de baja', 'Dado de baja'), ('Por definir', 'Por definir')], default='Por definir', max_length=20, verbose_name='Estado')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Observaciones')),
                ('screen', models.IntegerField(default='18', verbose_name='Pulgadas')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actives.modelmanufacturer', verbose_name='Fabricante')),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitores',
            },
        ),
        migrations.CreateModel(
            name='EquipmentMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('maintenance_type', models.CharField(choices=[('Correctivo', 'Correctivo'), ('Preventivo', 'Preventivo')], default='Por definir', max_length=20, verbose_name='Tipo Proceso')),
                ('start_maintenance', models.DateField(verbose_name='Fecha de inicio mantenimiento')),
                ('end_maintenance', models.DateField(blank=True, null=True, verbose_name='Fecha de fin mantenimiento')),
                ('solution_description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Mantenimiento y solución')),
                ('problem_description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Problema y condiciones iniciales')),
                ('added_parts', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Piezas añadidas')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Observaciones')),
                ('priority', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja'), ('Por definir', 'Por definir')], default='Por definir', max_length=20, verbose_name='Prioridad')),
                ('maintenance_state', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En curso', 'En curso'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20, verbose_name='Estado Proceso')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actives.computers', verbose_name='Computador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Encargado')),
            ],
            options={
                'verbose_name': 'Mantenimiento Equipo',
                'verbose_name_plural': 'Mantenimientos Equipos',
            },
        ),
        migrations.CreateModel(
            name='DevicesMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('maintenance_type', models.CharField(blank=True, choices=[('Correctivo', 'Correctivo'), ('Preventivo', 'Preventivo')], default='Por definir', max_length=20, null=True, verbose_name='Tipo Proceso')),
                ('start_maintenance', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio mantenimiento')),
                ('end_maintenance', models.DateField(blank=True, null=True, verbose_name='Fecha de fin mantenimiento')),
                ('solution_description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Mantenimiento y solución')),
                ('problem_description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Problema y condiciones iniciales')),
                ('added_parts', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Piezas añadidas')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Observaciones')),
                ('priority', models.CharField(blank=True, choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja'), ('Por definir', 'Por definir')], default='Por definir', max_length=20, null=True, verbose_name='Prioridad')),
                ('maintenance_state', models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('En curso', 'En curso'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20, null=True, verbose_name='Estado Proceso')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actives.passivedevices', verbose_name='Computador')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Encargado')),
            ],
            options={
                'verbose_name': 'Mantenimiento Dispositivo',
                'verbose_name_plural': 'Mantenimientos Dispositivos',
            },
        ),
        migrations.AddField(
            model_name='computers',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actives.modelmanufacturer', verbose_name='Fabricante - Modelo'),
        ),
    ]
