# Generated by Django 4.1 on 2023-01-19 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actives', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentmaintenance',
            options={'verbose_name': 'Mantenimiento Equipo', 'verbose_name_plural': 'Mantenimientos Equipos'},
        ),
        migrations.CreateModel(
            name='DevicesMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('maintenance_type', models.CharField(blank=True, choices=[('Correctivo', 'Correctivo'), ('Preventivo', 'Preventivo')], default='Por definir', max_length=20, null=True, verbose_name='Tipo Proceso')),
                ('start_maintenance', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio mantenimiento')),
                ('end_maintenance', models.DateField(blank=True, null=True, verbose_name='Fecha de fin mantenimiento')),
                ('solution_description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Mantenimiento y solución')),
                ('problem_description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Problema y condiciones iniciales')),
                ('added_parts', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Piezas añadidas')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Observaciones')),
                ('priority', models.CharField(blank=True, choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja'), ('Por definir', 'Por definir')], default='Por definir', max_length=20, null=True, verbose_name='Prioridad')),
                ('maintenance_state', models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('En curso', 'En curso'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20, null=True, verbose_name='Estado Proceso')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actives.passivedevices', verbose_name='Computador')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Encargado')),
            ],
            options={
                'verbose_name': 'Mantenimiento Dispositivo',
                'verbose_name_plural': 'Mantenimientos Dispositivos',
            },
        ),
    ]
