# Generated by Django 4.1.5 on 2023-01-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='is_computer',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Es computador'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='is_device',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Es dispositivo'),
        ),
        migrations.AddField(
            model_name='modelmanufacturer',
            name='is_computer',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Es computador'),
        ),
        migrations.AddField(
            model_name='modelmanufacturer',
            name='is_device',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Es dispositivo'),
        ),
    ]
