# Generated by Django 4.1.5 on 2023-01-10 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actives', '0002_manufacturer_is_computer_manufacturer_is_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computers',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Asignación'),
        ),
        migrations.AddField(
            model_name='passivedevices',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Asignación'),
        ),
    ]
