# Generated by Django 4.1.5 on 2023-01-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0002_equipmentmaintenance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmaintenance',
            name='priority',
            field=models.CharField(blank=True, choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja'), ('Por definir', 'Por definir')], default='Por definir', max_length=20, null=True, verbose_name='Prioridad'),
        ),
    ]
