# Generated by Django 4.1 on 2023-01-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0002_alter_equipmentmaintenance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitors',
            name='screen',
            field=models.IntegerField(default='18', verbose_name='Pulgadas'),
        ),
    ]
