# Generated by Django 4.1.5 on 2023-01-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0003_alter_equipmentmaintenance_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmanufacturer',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Imagen producto'),
        ),
    ]
