# Generated by Django 4.1.5 on 2023-01-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0004_alter_modelmanufacturer_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmanufacturer',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen producto'),
        ),
    ]
