# Generated by Django 4.1 on 2023-04-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0001_initial'),
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignusers',
            name='others_computers',
            field=models.ManyToManyField(blank=True, related_name='others_computers', to='actives.computers', verbose_name='Otros Computadores'),
        ),
        migrations.AddField(
            model_name='assignusers',
            name='others_monitor',
            field=models.ManyToManyField(blank=True, related_name='others_monitor', to='actives.monitors', verbose_name='Otros Monitores'),
        ),
    ]
