# Generated by Django 4.1 on 2023-01-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignusers',
            name='type_assignment',
        ),
        migrations.AddField(
            model_name='assignusers',
            name='image_back_pc',
            field=models.ImageField(blank=True, null=True, upload_to='assign_user', verbose_name='Imagen Equipo debajo'),
        ),
        migrations.AddField(
            model_name='assignusers',
            name='image_devices',
            field=models.ImageField(blank=True, null=True, upload_to='assign_user', verbose_name='Imagen dispositivos'),
        ),
        migrations.AddField(
            model_name='assignusers',
            name='image_front_pc',
            field=models.ImageField(blank=True, null=True, upload_to='assign_user', verbose_name='Imagen Equipo frontal'),
        ),
        migrations.AddField(
            model_name='assignusers',
            name='image_keyboard',
            field=models.ImageField(blank=True, null=True, upload_to='assign_user', verbose_name='Imagen teclado'),
        ),
        migrations.AddField(
            model_name='assignusers',
            name='image_monitor',
            field=models.ImageField(blank=True, null=True, upload_to='assign_user', verbose_name='Imagen monitor'),
        ),
        migrations.AddField(
            model_name='assignusers',
            name='image_others',
            field=models.ImageField(blank=True, null=True, upload_to='assign_user', verbose_name='Imagen Otros elementos'),
        ),
        migrations.AddField(
            model_name='assignusers',
            name='image_up_pc',
            field=models.ImageField(blank=True, null=True, upload_to='assign_user', verbose_name='Imagen Equipo superior'),
        ),
    ]
