# Generated by Django 4.1.5 on 2023-01-16 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_assignusers_dni_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('name_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre completo')),
                ('email_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='Correo corporativo')),
                ('dni_user', models.IntegerField(blank=True, null=True, verbose_name='Documento de Identidad')),
                ('type_assignment', models.CharField(blank=True, choices=[('Contrato fijo', 'Contrato fijo'), ('Contrato indefinido', 'Contrato indefinido'), ('Prestamo', 'Prestamo'), ('Fijo al area', 'Fijo al area'), ('Aprendiz', 'Aprendiz'), ('Practicante', 'Practicante'), ('Contrato prestacion', 'Contrato prestacion'), ('Por definir', 'Por definir')], default='Por definir', max_length=20, null=True, verbose_name='Tipo asignación')),
            ],
        ),
        migrations.RemoveField(
            model_name='assignusers',
            name='dni_user',
        ),
        migrations.RemoveField(
            model_name='assignusers',
            name='email_user',
        ),
        migrations.RemoveField(
            model_name='assignusers',
            name='name_user',
        ),
        migrations.AddField(
            model_name='assignusers',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.userdata', verbose_name='Encargado'),
        ),
    ]
