# Generated by Django 4.1.5 on 2023-01-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_userdata_remove_assignusers_dni_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
