# Generated by Django 4.1.5 on 2023-01-18 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0003_alter_equipmentmaintenance_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment', '0004_alter_userdata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignusers',
            name='computers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actives.computers', verbose_name='Equipo asignado'),
        ),
        migrations.AlterField(
            model_name='assignusers',
            name='date_assignment',
            field=models.DateField(verbose_name='Fecha de asignación'),
        ),
        migrations.AlterField(
            model_name='assignusers',
            name='type_assignment',
            field=models.CharField(choices=[('Contrato fijo', 'Contrato fijo'), ('Contrato indefinido', 'Contrato indefinido'), ('Prestamo', 'Prestamo'), ('Fijo al area', 'Fijo al area'), ('Aprendiz', 'Aprendiz'), ('Practicante', 'Practicante'), ('Contrato prestacion', 'Contrato prestacion'), ('Por definir', 'Por definir')], default='Por definir', max_length=20, verbose_name='Tipo asignación'),
        ),
        migrations.AlterField(
            model_name='assignusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Encargado'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='dni_user',
            field=models.IntegerField(verbose_name='Documento de Identidad'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email_user',
            field=models.CharField(max_length=150, verbose_name='Correo corporativo'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='name_user',
            field=models.CharField(max_length=150, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='type_assignment',
            field=models.CharField(choices=[('Contrato fijo', 'Contrato fijo'), ('Contrato indefinido', 'Contrato indefinido'), ('Prestamo', 'Prestamo'), ('Fijo al area', 'Fijo al area'), ('Aprendiz', 'Aprendiz'), ('Practicante', 'Practicante'), ('Contrato prestacion', 'Contrato prestacion'), ('Por definir', 'Por definir')], default='Por definir', max_length=20, verbose_name='Tipo asignación'),
        ),
    ]
