# Generated by Django 4.1.5 on 2023-01-18 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0003_alter_equipmentmaintenance_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment', '0005_alter_assignusers_computers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignusers',
            name='computers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actives.computers', verbose_name='Equipo asignado'),
        ),
        migrations.AlterField(
            model_name='assignusers',
            name='date_assignment',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de asignación'),
        ),
        migrations.AlterField(
            model_name='assignusers',
            name='type_assignment',
            field=models.CharField(blank=True, choices=[('Contrato fijo', 'Contrato fijo'), ('Contrato indefinido', 'Contrato indefinido'), ('Prestamo', 'Prestamo'), ('Fijo al area', 'Fijo al area'), ('Aprendiz', 'Aprendiz'), ('Practicante', 'Practicante'), ('Contrato prestacion', 'Contrato prestacion'), ('Por definir', 'Por definir')], default='Por definir', max_length=20, null=True, verbose_name='Tipo asignación'),
        ),
        migrations.AlterField(
            model_name='assignusers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Encargado'),
        ),
    ]
