# Generated by Django 4.1.5 on 2023-01-18 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0004_alter_modelmanufacturer_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment', '0006_alter_assignusers_computers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignusers',
            name='assignment',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='assignment.userdata', verbose_name='Encargado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignusers',
            name='computers',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='actives.computers', verbose_name='Equipo asignado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignusers',
            name='date_assignment',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de asignación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignusers',
            name='type_assignment',
            field=models.CharField(choices=[('Contrato fijo', 'Contrato fijo'), ('Contrato indefinido', 'Contrato indefinido'), ('Prestamo', 'Prestamo'), ('Fijo al area', 'Fijo al area'), ('Aprendiz', 'Aprendiz'), ('Practicante', 'Practicante'), ('Contrato prestacion', 'Contrato prestacion'), ('Por definir', 'Por definir')], default='Por definir', max_length=20, verbose_name='Tipo asignación'),
        ),
        migrations.AlterField(
            model_name='assignusers',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Encargado'),
            preserve_default=False,
        ),
    ]
